# Generated by Django 2.1.7 on 2019-03-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('type', models.CharField(blank=True, choices=[('c', 'cup'), ('cl', 'clove'), ('tsp', 'teaspoon'), ('oz', 'ounce'), ('lb', 'pound'), ('tbsp', 'tablespoon')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('forked_from', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recipes.Recipe')),
                ('ingredients', models.ManyToManyField(blank=True, to='recipes.Ingredient')),
                ('materials', models.ManyToManyField(blank=True, to='recipes.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('note', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(blank=True, to='recipes.Step'),
        ),
    ]
