# Generated by Django 2.1.7 on 2019-03-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=3)),
                ('type', models.CharField(choices=[(4, 'ounce'), (1, 'teaspoon'), (2, 'tablespoon'), (5, 'pound'), (6, 'clove'), (3, 'cup')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('numbered', models.BooleanField()),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='recipes.Step'),
        ),
    ]
