# Generated by Django 2.1.7 on 2019-03-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190311_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[(6, 'clove'), (1, 'teaspoon'), (2, 'tablespoon'), (3, 'cup'), (4, 'ounce'), (5, 'pound')], max_length=32),
        ),
    ]
