# Generated by Django 2.1.7 on 2019-03-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190311_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('tbsp', 'tablespoon'), ('oz', 'ounce'), ('tsp', 'teaspoon'), ('cl', 'clove'), ('c', 'cup'), ('lb', 'pound')], max_length=32),
        ),
        migrations.AddField(
            model_name='recipe',
            name='materials',
            field=models.ManyToManyField(to='recipes.Material'),
        ),
    ]
