# Generated by Django 2.1.7 on 2019-03-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190311_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='numbered',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='step',
            name='number',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('lb', 'pound'), ('oz', 'ounce'), ('c', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('cl', 'clove')], max_length=32),
        ),
    ]
