# Generated by Django 2.1.7 on 2019-03-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190311_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('oz', 'ounce'), ('tbsp', 'tablespoon'), ('lb', 'pound'), ('tsp', 'teaspoon'), ('c', 'cup'), ('cl', 'clove')], max_length=32),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='materials',
            field=models.ManyToManyField(blank=True, to='recipes.Material'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(blank=True, to='recipes.Step'),
        ),
    ]
